[auth]
	# Private GitHub and/or GitLab token which allow proji to access private repos and benefit from things like an extended rate limiting.
	gh_token = ""
	gl_token = ""

[core]
	# Option to disable cli colors by default.
	disable_colors = false

[database]
	# Supported drivers: mysql, mssql, postgres, sqlite3
	driver = "sqlite3"
	# Connection string to the database. See https://gorm.io/docs/connecting_to_the_database.html#Supported-Databases for more informations.
	# Note: In case of sqlite the dsn may hold an absolute or relative path. A relative path is thought to be relative to projis root config
	# folder. So internally the example below gets interpreted as '/home/[USER]/.config/proji/db/proji.sqlite3'.
	dsn = "db/proji.sqlite3"

[import]
	# Specify a regex which will be used on directory/repository structure and collection imports. This regex is used to exclude
	# folders and files from being imported.
	# You can extend the example filter down below or pass the '-e' / '--exclude' flag when importing a package from the previously
	# named sources. If you pass a valid regex to the exclude flag it will overwrite the regex specified in your config during runtime but not
	# persistently.
	exclude = "^(.git|.env|.idea|.vscode)$"
